### ISSUE TITLE
Merge Conflicts 

### ISSUE THREAD

**Issue by AI-Pranto** [openmc-dev/plotter#38]
Merge conflicts occur betwwen 
1. check_statepoint
2. mesh_yt
3. reorganize_menus  
branches.

**Comment by pshriwise** [comment]
Hi @AI-Pranto! 

Are you maybe referring to the branches in my fork (https://github.com/pshriwise/plotter)? If so, I'd plan on resolving those conflicts before submitting them to this repo.

If you have immediate need of any of these features, I can address them sooner. Otherwise I'll close this issue as it relates to a fork and not code in this repo itself.

**Comment by AI-Pranto** [comment]
Sir,
Thanks for your reply and I already close the issue. If you kindly address
those features , it will be very helpful for me.

best regards
Pranto
