### ISSUE TITLE
installation issue with openmc-0.12-dev

### ISSUE THREAD

**Issue by khurrumsaleem** [openmc-dev/plotter#45]
Hello @pshriwise and @paulromano 

I hope you are doing well. I tried installing the plotter using python3 setup.py build and then python3 setup.py install. build went OK but install gives error that openmc not found although when i use pip list command it shows both of them installed side by side and i am using openmc using ipython.
![image](https://user-images.githubusercontent.com/5681739/89566573-d2d2fe80-d839-11ea-96c8-ca043f541220.png)

secondly with the recent changes (installation and others), i can't seem to run the plotter anyhow. I have used the python /path/to/openmc-plotter and other variants. 

your help in this regard will be appreciated

**Comment by pshriwise** [comment]
Hi @khurrumsaleem. Happy to help w/ this.

It is sometimes possible that the versions of Python used to install these packages are not the same when one is installed with Python and the other with pip. It's a little confusing because `pip list` is able to find both the `openmc` and `openmc-plotter` packages in these situations. I'd recommend reinstalling both the `openmc` and `openmc-plotter` packages using pip for both by running `pip install .` each of those repositories to ensure the Python version used to install and run these packages is the same.

**Comment by khurrumsaleem** [comment]
Thanks @pshriwise 

Yes installation went smoothly using pip. 

but on the other front, how to run it. I am not able to run it using the command given in readme.md

**Comment by pshriwise** [comment]
Unfortunately the readme is a bit out of date. You should be able to run `$ openmc-plotter` in a directory with an openmc model.

**Comment by pshriwise** [comment]
I'll make a PR shortly with an update to the readme instructions.

**Comment by khurrumsaleem** [comment]
thank you @pshriwise

**Comment by pshriwise** [comment]
Addressed in #46.
