### ISSUE TITLE
Create conda-forge package for plotter

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/plotter#92]
Several people have run into problems trying to install the plotter while using conda. It would be pretty easy for us to put together a conda-forge package for the plotter to avoid any issues with conflicting Qt installations, etc.

**Comment by kkiesling** [comment]
@paulromano and @pshriwise - do you both want to be maintainers on this package?

**Comment by pshriwise** [comment]
Sure, sign me up!

**Comment by paulromano** [comment]
Why not, sign me up too :smile:

**Comment by kkiesling** [comment]
excellent- you can both explicitly consent to being maintainers on this [PR](https://github.com/conda-forge/staged-recipes/pull/18849).

**Comment by kkiesling** [comment]
Our feedstock is officially a go: https://github.com/conda-forge/openmc-plotter-feedstock

Note, that any future changes to the feedstock WILL have a windows CI failure due to no OpenMC for windows. I have been assured by the conda-forge team that this is the correct way to handle missing dependencies.

This issue can be closed now.
